name: Deploy to Production

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract tag name
      id: extract_tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
    - name: Build and push Frontend with tag
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/customer-management-frontend:${{ steps.extract_tag.outputs.tag }}
          ${{ secrets.DOCKER_USERNAME }}/customer-management-frontend:latest
          
    - name: Build and push Backend with tag
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/customer-management-backend:${{ steps.extract_tag.outputs.tag }}
          ${{ secrets.DOCKER_USERNAME }}/customer-management-backend:latest
          
    - name: Deploy to production
      run: |
        echo "Deploying version ${{ steps.extract_tag.outputs.tag }} to production"
        # Add your deployment commands here
